version: '2'
services:
    library-app:
        image: library
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://library-postgresql:5432/Library
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    library-postgresql:
        extends:
            file: postgresql.yml
            service: library-postgresql
